config/routes.rb
Touchstone::Engine.routes.draw do
  
  root :to => 'dashboard#dashboard'
  match 'dashboard' => 'dashboard#dashboard'
  resources :campaigns
  
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  
  validates :name, :presence => true
  validates :spend_amount, :presence => true
  
  has_many :campaign_signups
  has_many :campaign_visits
  
  attr_accessible :name, :notes, :start_date, :end_date, :spend_amount
  
  def revenue
    if self.campaign_signups.length > 0
      total = Array.new
      self.campaign_signups.each do |signup|
        total << signup.user.lifetime_value
      end
      total.inject{|sum,x| sum + x}
    else
      0.00
    end
  end
  
  def roi
    if self.revenue == 0 || self.spend_amount == 0
      0.00
    else
      ((self.revenue - self.spend_amount) / self.spend_amount) * 100
    end
  end
  
  def visits
    self.campaign_visits.count
  end
  
  def conversion_rate
    signups = self.campaign_signups.count
    if signups > 0
      (signups.to_f / self.visits.to_f ) * 100
    else
      0.00
    end
  end
  
end

app/models/campaign_signup.rb
class CampaignSignup < ActiveRecord::Base
  
  belongs_to :campaign, :class_name => "Campaign", :foreign_key => "campaign_id"
  belongs_to :user, :class_name => Touchstone.association_name.capitalize, :foreign_key => "#{Touchstone.association_name}_id" # TODO: Fix this
  
  attr_accessible "#{Touchstone.association_name}_id".to_sym, :campaign_id
  
end

app/models/campaign_visit.rb
class CampaignVisit < ActiveRecord::Base
  
  belongs_to :campaign, :class_name => "Campaign", :foreign_key => "campaign_id"
  
  attr_accessible :campaign_id, :request_ip
  
end

app/models/touchstone_event.rb
class TouchstoneEvent < ActiveRecord::Base
  
  attr_accessible :event, :model_name
  
  def self.signups_in(month,year)
    start_date = Date.new(year,month,1,0)
    end_date = start_date.end_of_month
    where(:created_at => (start_date..end_date), :event => "create").count
  end
  
  def self.cancellations_in(month,year)
    start_date = Date.new(year,month,1,0)
    end_date = start_date.end_of_month
    where(:created_at => (start_date..end_date), :event => "destroy").count
  end
  
end

app/controllers/touchstone/application_controller.rb
module Touchstone
  class ApplicationController < ActionController::Base
    
    if Touchstone.authenticate == true
      config = YAML::load(File.open("#{Rails.root}/config/touchstone.yml"))
      http_basic_authenticate_with :name => config['name'], :password => config['password']
    end
    
  end
end

app/controllers/touchstone/campaigns_controller.rb
module Touchstone
  class CampaignsController < ApplicationController
  
    layout 'touchstone/touchstone'
  
    def index
      @campaigns = Campaign.includes(:campaign_signups).all
    end
  
    def new
      @campaign = Campaign.new
    end
  
    def create
      @campaign = Campaign.new(params[:campaign])
      if @campaign.save
        flash[:notice] = "Campaign added"
        redirect_to campaigns_url
      else
        flash[:error] = "Could not add campaign"
        redirect_to new_campaign_url
      end
    end
  
    def show
      @campaign = Campaign.find(params[:id])
      @columns = Touchstone.column_names
    end
  
    def edit
      @campaign = Campaign.find(params[:id])
    end
  
    def update
      @campaign = Campaign.find(params[:id])
      if @campaign.update_attributes(params[:campaign]) && @campaign.save
        flash[:notice] = "Campaign details updated"
        redirect_to campaign_path(@campaign)
      else
        flash[:error] = "Could not update details at this time."
        redirect_to campaign_path(@campaign)
      end
    end
  
  end
end

app/controllers/touchstone/dashboard_controller.rb
module Touchstone
  class DashboardController < ApplicationController
    
    layout 'touchstone/touchstone'
    
    ASSOCIATION_NAME = Touchstone.association_name.capitalize.constantize
    
    def dashboard
      @costs = Touchstone.costs
      @month = Date.today.month
      @year = Date.today.year
      if request.post?
        @month = params[:date][:month].to_i
        @year = params[:date][:year].to_i
      end
      total_users,new_users,churn,current_users,cancellations,cmrr = Array.new,Array.new,Array.new,Array.new,Array.new,Array.new
      @range = (@month-2..@month)
      @top_line = Hash.new
      @bottom_line = Hash.new
      
      @range.each{|n| total_users << ASSOCIATION_NAME.where('created_at < ?',Date.new(@year,n,1,0).end_of_month).count}
      @range.each{|n| new_users << TouchstoneEvent.signups_in(n,@year)}
      @range.each_with_index{|n,index| churn << sprintf("%.2f %",TouchstoneEvent.cancellations_in(n,@year) / total_users[index].to_f * 100)}
      avg_lifetime = churn.map{|c| sprintf("%.2f months", 100/c.to_f) }
      @range.each{|n| current_users << ASSOCIATION_NAME.where('created_at < ?',Date.new(@year,n-1,1,0).end_of_month).count}
      @range.each{|n| cancellations << TouchstoneEvent.cancellations_in(n,@year)}
      @range.each do |n|
        users = ASSOCIATION_NAME.where('created_at < ?',Date.new(@year,n,1,0).end_of_month)
        total = Array.new
        users.each{|u| total << u.monthly_revenue}
        cmrr << "#{Touchstone.currency}#{total.inject{|sum,x| sum + x}}"
      end
      %w(churn avg_lifetime current_users cancellations new_users total_users cmrr).each do |w|
        @top_line[w] = eval(w)
      end
      
      cost_per_user,cost_per_acquisition = Array.new,Array.new
      @range.each_with_index{|n,index| cost_per_user << sprintf("#{Touchstone.currency}%.2f",(@costs[:total_cost].to_f / total_users[index].to_f))}
      @range.each_with_index{|n,index| cost_per_acquisition << sprintf("#{Touchstone.currency}%.2f",(@costs[:marketing].to_f / total_users[index].to_f))}
      %w(cost_per_user cost_per_acquisition).each do |w|
        @bottom_line[w] = eval(w)
      end
    end
    
  end
end

app/helpers/touchstone/application_helper.rb
module Touchstone
  module ApplicationHelper
  end
end

app/helpers/touchstone/campaigns_helper.rb
module Touchstone
  module CampaignsHelper
    
    def signups_table_headers(columns)
      item = ""
      columns.each do |column|
        item += "<th scope='col' id='#{column}'>#{column.humanize}</th>\n"
      end
			item.html_safe
    end
    
    def signups_table_content(columns,signup)
      item = ""
      columns.each do |column|
        item += "<td class='#{column}'>#{signup.user.send(column.to_sym)}</td>\n"
      end
			item.html_safe
    end
    
  end
end

app/helpers/touchstone/dashboard_helper.rb
module Touchstone
  module DashboardHelper
    
   def total_users(month)
     
   end 
    
  end
end

app/views/campaigns/touchstone/index.html.erb
<p id="new-campaign"><%= link_to "New campaign", new_metrics_campaign_url %></p>

<h1>Campaigns</h1>

<table>
	<thead>
		<tr>
			<th scope="col" width="15%">Campaign ID</th>
			<th scope="col" width="36%">Name</th>
			<th scope="col" width="17%">Start date</th>
			<th scope="col" width="17%">End date</th>
			<th scope="col" width="15%">Spend amount</th>
		</tr>
	</thead>
	<tbody>
	<% @campaigns.each do |campaign| %>
		<tr>
			<td><%= campaign.id %></td>
			<td><%= link_to "#{campaign.name}", metrics_campaign_url(campaign.id) %></td>
			<td><%= campaign.start_date.strftime("%d %B %Y") %></td>
			<td><%= campaign.end_date.strftime("%d %B %Y") %></td>
			<td>$<%= sprintf("%.2f", campaign.spend_amount) %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/campaigns/touchstone/show.html.erb
<p><%= link_to "Home", metrics_campaigns_url %></p>

<h1>Campaign - <%= @campaign.name %></h1>

<section id="campaign-info">
	<p><strong>Campaign ID:</strong> <%= @campaign.id %></p>

	<p><strong>Campaign dates:</strong> From <%= @campaign.start_date.strftime("%d %B %Y") %> to <%= @campaign.end_date.strftime("%d %B %Y") %></p>
</section><!-- #campaign-info -->

<section id="financials" class="stats">
	<h3><span class="financial-title">Campaign Spend:</span> $<%= sprintf("%.2f", @campaign.spend_amount) %></h3> 
	<h3><span class="financial-title">Campaign Revenue:</span> $<%= sprintf("%.2f", @campaign.revenue) %></h3>
	<h3><span class="financial-title">Return on investment:</span> <%= sprintf("%.2f", @campaign.roi) %>%</h3>
</section>

<section id="visits" class="stats">
	<h3><span class="visit-title">Unique Campaign Visits:</span> <%= @campaign.visits %></h3>
	<h3><span class="visit-title">Conversion Rate:</span> <%= sprintf("%.2f",@campaign.conversion_rate) %>%</h3>
</section>

<h2>Signups via this campaign</h2>

<table>
	<thead>
		<tr>
			<th scope="col" width="25%">Name</th>
			<th scope="col" width="30%">Email</th>
			<th scope="col" width="30%">Registered</th>
			<th scope="col" width="15%">LTV (inc. VAT)</th>
		</tr>
	</thead>
	<tbody>
	<% @campaign.campaign_signups.each do |signup| %>
		<tr>
			<td><%= signup.user.name %></td>
			<td><%= signup.user.email %></td>
			<td><%= time_ago_in_words(signup.user.created_at) %> ago</td>
			<td>$<%= sprintf("%.2f",signup.user.lifetime_value) %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/layouts/touchstone/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Touchstone</title>
  <%= stylesheet_link_tag    "touchstone/application", :media => "all" %>
  <%= javascript_include_tag "touchstone/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/touchstone/touchstone.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Touchstone Metrics</title>
		<%= stylesheet_link_tag "touchstone/application.css" %>
	  <%= javascript_include_tag "touchstone/application.js" %>
	  <%= csrf_meta_tag %>
	</head>
	<body class="touchstone">
	 <header class="navbar navbar-fixed-top">
	   <nav class="navbar-inner">
	     <div class="container">
	       <h1 class="brand"><%= link_to "Touchstone Metrics", root_url %></h1>
	     </div>
	   </nav>
	 </header>
	 <div id="main" role="main">
	   <div class="container">
	     <div class="content">
	        <div class="row">
	         	<div class="span12">
							<% flash.each do |key, value| -%>
								<div class="alert alert-<%= key %>">
									<a class="close" data-dismiss="alert">×</a>
									<p><%= value.html_safe %></p>
								</div><!-- eo .alert -->
							<% end -%>
							
							<%= yield %>
						</div><!-- eo .span12 -->
					</div><!-- eo .row -->
				</div><!-- eo .content -->
				<footer>
				</footer>
			</div> <!--! end of .container -->
		</div> <!--! end of #main -->
	</body>
</html>

app/views/touchstone/campaigns/_campaign_form.html.erb
<%= form_for @campaign, :html => {:class => "well span6"} do |f| %>
	
	<div class="control-group">
		<%= f.label :name, :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :name %>
		</div><!-- eo .controls -->
	</div><!-- eo .control-group -->
	
	<div class="control-group">
		<%= f.label :notes, :class => "control-label" %>
		<div class="controls">
			<%= f.text_area :notes, :class => "span6", :rows => 5 %>
		</div><!-- eo .controls -->
	</div><!-- eo .control-group -->
	
	<div class="control-group">
		<%= f.label :start_date, :class => "control-label" %>
		<div class="controls">
			<%= f.date_select :start_date, :order => [:day, :month, :year] %>
		</div><!-- eo .controls -->
	</div><!-- eo .control-group -->
	
	<div class="control-group">
		<%= f.label :end_date, :class => "control-label" %>
		<div class="controls">
			<%= f.date_select :end_date, :order => [:day, :month, :year] %>
		</div><!-- eo .controls -->
	</div><!-- eo .control-group -->
	
	<div class="control-group">
		<%= f.label :spend_amount, :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :spend_amount %>
		</div><!-- eo .controls -->
	</div><!-- eo .control-group -->
	
	<p>
		<%= f.submit :class => "btn btn-primary" %> or <%= link_to "cancel", campaigns_path %>
	</p>
	
<% end %>

app/views/touchstone/campaigns/edit.html.erb
<div class="page-header"><h1>Edit Campaign</h1></div>

<%= render :partial => 'campaign_form' %>

app/views/touchstone/campaigns/index.html.erb
<div class="page-header">
	<%= link_to "<i class='icon-plus icon-white'></i>&nbsp;New campaign".html_safe, new_campaign_url, :class => "btn btn-primary" %>
	<h1>Campaigns</h1>
</div><!-- eo .page-header -->

<table class="table table-striped">
	<thead>
		<tr>
			<th scope="col" width="15%">Campaign ID</th>
			<th scope="col" width="30%">Name</th>
			<th scope="col" width="17%">Start date</th>
			<th scope="col" width="17%">End date</th>
			<th scope="col" width="15%">Spend amount</th>
			<th scope="col" width="6%">Visits</th>
		</tr>
	</thead>
	<tbody>
	<% @campaigns.each do |campaign| %>
		<tr>
			<td><%= campaign.id %></td>
			<td><%= link_to "#{campaign.name}", campaign_url(campaign.id) %></td>
			<td><%= campaign.start_date.strftime("%d %B %Y") %></td>
			<td><%= campaign.end_date.strftime("%d %B %Y") %></td>
			<td><%= Touchstone.currency %><%= sprintf("%.2f", campaign.spend_amount) %></td>
			<td><%= campaign.campaign_signups.count %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/touchstone/campaigns/new.html.erb
<div class="page-header"><h1>New campaign</h1></div>

<%= render :partial => 'campaign_form' %>

app/views/touchstone/campaigns/show.html.erb
<div class="page-header">
	<%= link_to "<i class='icon-pencil'></i>&nbsp;Edit".html_safe, edit_campaign_url(@campaign), :class => "btn" %>
	<%= link_to "<i class='icon-home icon-white'></i>&nbsp;Home".html_safe, campaigns_url, :class => "btn btn-primary" %>
	<h1>Campaign - <%= @campaign.name %>&nbsp;<small><abbr title="Append this to the end of each link used in this campaign e.g. http://yourdomain.com/?cid=1">?cid=<%= @campaign.id %></abbr></small></h1>
</div><!-- eo .page-header -->

<section id="campaign-info">
	<% if @campaign.end_date < Date.today %>
		<p class="ended">This campaign has ended.</p>
	<% else %>
		<p class="running">This campaign is currently running.</p>
	<% end %>
</section><!-- #campaign-info -->

<section id="financials" class="stats">
	<h3>Campaign Spend: <span><%= Touchstone.currency %><%= sprintf("%.2f", @campaign.spend_amount) %></span></h3> 
	<h3>Campaign Revenue: <span><%= Touchstone.currency %><%= sprintf("%.2f", @campaign.revenue) %></span></h3>
	<h3>Return on investment: <span><%= sprintf("%.2f", @campaign.roi) %>%</span></h3>
</section>

<section id="visits" class="stats">
	<h3>Unique Campaign Visits: <span><%= @campaign.visits %></span></h3>
	<h3>Conversion Rate: <span><%= sprintf("%.2f",@campaign.conversion_rate) %>%</span></h3>
</section>

<h2>Signups via this campaign</h2>

<table class="table table-striped">
	<thead>
		<tr>
			<%= signups_table_headers(@columns) %>
		</tr>
	</thead>
	<tbody>
	<% @campaign.campaign_signups.each do |signup| %>
		<tr>
			<%= signups_table_content(@columns,signup)%>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/touchstone/dashboard/dashboard.html.erb
<div class="page-header">
	<h1>Dashboard</h1>
	<p>3 months to <%= form_tag '/touchstone/dashboard' do %><%= select_month(@month) %><%= select_year(@year) %><%= submit_tag "Go" %><% end %></p>
</div>
<p>Figures represent the position at the end of a given month.</p>
<table class="table">
	<thead>
		<tr>
			<th>Metric</th>
			<% @range.each do |n| %>
				<th><%= Date::MONTHNAMES[n] %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @top_line.each do |key,values| %>
		<tr>
			<td><strong><%= key.humanize.upcase %></strong></td>
			<% values.each do |v| %>
				<td><%= v %></td>
			<% end %>
		</tr>
		<% end %>
		
		<% @costs.each do |key,value| %>
		<tr>
			<td><strong><%= key.to_s.humanize.upcase %></strong></td>
			<% @range.to_a.length.times do %>
				<td><%= Touchstone.currency %><%= value %></td>
			<% end %>
		</tr>
		<% end %>
		
		<% @bottom_line.each do |key,values| %>
		<tr>
			<td><strong><%= key.humanize.upcase %></strong></td>
			<% values.each do |v| %>
				<td><%= v %></td>
			<% end %>
		</tr>
		<% end %>
		
	</tbody>
</table>